### ISSUE TITLE
Try for Malaysia custom projection

### ISSUE THREAD

**Issue by saifulazfar** [rveciana/d3-composite-projections#9]
- NOT AN ISSUE ABOUT d3-composite-projection

Sorry noob here trying to create custom composite projection for Malaysia though, i tried to follow the calculations from EquadorMercator but seems my graticule looks ugly,

[http://bl.ocks.org/saifulazfar/76053d7a7d420a3a0bc0fb5849006309](http://bl.ocks.org/saifulazfar/76053d7a7d420a3a0bc0fb5849006309)

FYI world-50m.json also attached with the gist, i recommend you try with the world data also, need advice with the clipping

any help or advise welcome

**Comment by rveciana** [comment]
The problem with graticule lines is because the two zones of the composite projection overlap. If you look at the projection for Ecuador: http://bl.ocks.org/rveciana/29671e257e9e724d2857f726844777b6 you'll see that the lines can be drawn without problem, because the two zones are completely separated. In your case, you could try separating the two zones a little and set the zone projections to fit the land parts so they don't overlap.
If you finish the projection, please tell me, I could add it to the d3-composite-projections so everybody can use it, if you want.

**Comment by saifulazfar** [comment]
thank you...yes i think i should seperate them rather than overlap

![2](https://cloud.githubusercontent.com/assets/8967580/22247021/afefe286-e272-11e6-8ba3-a8700d84115a.jpg)

by the way how could the mbostock example of [AlbersUSA + PR](https://bl.ocks.org/mbostock/5629120) zones of the composite projection overlap? it seems alaska, hawaii and puerto rico drawn into lower48 bounding box...is it because of the alberUsa projection that already on d3.geo? same goes how i try to achieved to as peninsular draw on top of borneo bounding box...is it possible that way?

![1](https://cloud.githubusercontent.com/assets/8967580/22247041/bf1518d0-e272-11e6-8b80-7c32cb9d93e3.jpg)

**Comment by rveciana** [comment]
Graticule lines can create strange effects if the projection area is not clipped properly. But sometimes it may work.
I the US, the different zones are very separated, so maybe the meridians and parallels are not twice in the same image, so they don't create these effects.
